### ISSUE TITLE
Project ownership

### ISSUE THREAD

**Issue by erykpiast** [grafana-druid-plugin/druidplugin#100]
@abhisant @Gauravshah are you still maintaining the project? I can see a lot of open issues and PRs not merged for a long time. I'd like to implement support for `quantilesDoublesSketch`, but barely see a chance of merging it. Do you need some help with merging existing PRs first?

**Comment by mickymiek** [comment]
Seeing this: https://github.com/grafana-druid-plugin/druidplugin/issues/91, I hope you'll get a feedback...
I think the best solution now is to migrate to the most active fork (https://github.com/GoshPosh/druidplugin I think) or create a new one

**Comment by mickymiek** [comment]
Actually @abhisant gave us (@jbguerraz, @Gauravshah and me) rights to maintains this plugin. We'll start reviving this repo ASAP :)

**Comment by erykpiast** [comment]
That’s a great news! @jln-pl will have a PR for you I suppose :)
