### ISSUE TITLE
druidplugin does not support alerting

### ISSUE THREAD

**Issue by HoraceLee** [grafana-druid-plugin/druidplugin#108]
druidplugin does not support alerting queries which is a very useful feature.
![image](https://user-images.githubusercontent.com/9915526/103866167-4edeb480-5100-11eb-9130-1be671c00125.png)

**Comment by Gauravshah** [comment]
duplicate of https://github.com/grafana-druid-plugin/druidplugin/issues/21

**Comment by jbguerraz** [comment]
@HoraceLee  feel free to take a look on https://github.com/grafana-druid-plugin/druidplugin/issues/107
This new plugin supports alerting.
