### ISSUE TITLE
When I add a variable

### ISSUE THREAD

**Issue by WANGLULU9802** [grafana-druid-plugin/druidplugin#118]
When I add variables of time, I can't choose the query mode.An error as shown in the figure below.Somebody help me please.

Templating [task_name]
Error updating options: Couldn't find a query runner that matches supplied arguments.

Validation
Couldn't find a query runner that matches supplied arguments.

**Comment by jbguerraz** [comment]
Hello @WANGLULU9802 
This project isn't much supported by now.
Feel free to take a look on its successor: https://grafana.com/grafana/plugins/grafadruid-druid-datasource/
