### ISSUE TITLE
Support SQL of the upcoming Druid 0.10

### ISSUE THREAD

**Issue by knoguchi** [grafana-druid-plugin/druidplugin#13]
The upcoming Druid 0.10 supports SQL query.  I would like to support the feature.
http://druid.io/docs/0.10.0-rc1/querying/sql.html

The server side SQL is more promising than the client side PlyQL and Plywood.  I'm hoping the SQL syntax is expressive enough to support the full capability of the native Druid queries.

If so, we will not have to write filters, aggs, post-aggs, time bucketing, or switching topN for single dimension and groupBy for multi dimensions, etc, etc.

**Comment by abhisant** [comment]
Sure. Thanks @knoguchi

**Comment by knoguchi** [comment]
I decided to add Druid to https://github.com/sraoss/grafana-sqldb-datasource instead of this plugin.
