### ISSUE TITLE
Any panel type support the result of approxHistogramFold query in druid?

### ISSUE THREAD

**Issue by elloooooo** [grafana-druid-plugin/druidplugin#14]
When I you use approxHistogramFold query, There is no data points in Graph or Table panel. Any suggestion or doc for me？

**Comment by abhisant** [comment]
Provided the doc through email. Long back, please let me know if you still have this issue.

**Comment by nanittu** [comment]
@abhisant can you email the doc to me too ? mithun.yarlagadad@gmail.com
