### ISSUE TITLE
Custom templates do not work in Graph -> Matrics

### ISSUE THREAD

**Issue by CarsonCao** [grafana-druid-plugin/druidplugin#15]
I created a custom template variable named 'items' with values 'url' and 'ip'. And I wanted to use it in dimension of matrics  in order to  allow the graph to dynamically display different information. But it does not work. 
However ,the template variable in title works well.

The panel JSON like below.
----------------------------------------------
{
  "aliasColors": {},
  "bars": true,
  "dashLength": 10,
  "dashes": false,
  "datasource": "druid_test",
  "fill": 1,
  "id": 2,
  "legend": {
    "alignAsTable": true,
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "rightSide": true,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": false,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "repeat": null,
  "seriesOverrides": [],
  "spaceLength": 10,
  "span": 12,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "aggregators": [
        {
          "fieldName": "counts",
          "name": "counts",
          "type": "longSum"
        }
      ],
      "currentAggregator": {
        "type": "count"
      },
      "currentFilter": {
        "type": "selector"
      },
      "currentPostAggregator": {
        "fn": "+",
        "type": "arithmetic"
      },
      "currentSelect": {
        "dimension": "",
        "metric": ""
      },
      "customGranularity": "all",
      "dimension": "$items",
      "druidDS": "url_ip_test",
      "druidMetric": "counts",
      "errors": {
        "aggregators": "You must supply at least one aggregator"
      },
      "limit": 10,
      "queryType": "topN",
      "refId": "A",
      "shouldOverrideGranularity": true
    }
  ],
  "thresholds": [],
  "timeFrom": "$timeRange",
  "timeShift": null,
  "title": "[[items]] top10",
  "tooltip": {
    "shared": false,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "series",
    "name": null,
    "show": false,
    "values": [
      "total"
    ]
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}

**Comment by knoguchi** [comment]
Here is a quick hack to apply the template variable on groupBy field.

```
diff --git a/src/datasource.js b/src/datasource.js
index a79c8fc..7b7991e 100644
--- a/src/datasource.js
+++ b/src/datasource.js
@@ -115,7 +115,7 @@ function (angular, _, dateMath, moment) {
       var filters = target.filters;
       var aggregators = target.aggregators;
       var postAggregators = target.postAggregators;
-      var groupBy = target.groupBy;
+      var groupBy = _.map(target.groupBy, (e) => { return templateSrv.replace(e) });
       var limitSpec = null;
       var metricNames = getMetricNames(aggregators, postAggregators);
       var intervals = getQueryIntervals(from, to);
```

**Comment by CarsonCao** [comment]
@knoguchi How about the dimension field?

**Comment by CarsonCao** [comment]
@knoguchi Thank you for your solution. I modified the code according to your way on dimension field, but it did not work. What should I do?

**Comment by knoguchi** [comment]
The code that I showed is for groupby query only.

Please select groupBy and put the template variable name in the dimension
field.  If the template variable name is x, pls put $x in the dimension
field.

**Comment by CarsonCao** [comment]
@knoguchi I know that. It works for GroupBy.But it don't work in TopN.

**Comment by knoguchi** [comment]
You didn't even mention TopN besides the JSON.    I hoped you'd get the idea as to how the template variables work in Grafana.   It's easy to apply the same fix for other fields.

Created a PR #16.

**Comment by amoussoubaruch** [comment]
hi @CarsonCao 

I'm just starting using grafana and druid. How can you create template variable. I do not find any documentation for that. 
Can you please send my a link or any exemple can help me to advance. 

Thanks
