### ISSUE TITLE
Doc needed for the approxhistogramfold option

### ISSUE THREAD

**Issue by nanittu** [grafana-druid-plugin/druidplugin#19]
I couldn't get the quantiles data i want to with the post aggregation option and "approxhistogramfold" aggregator. the panel returns with no data points. Is there a usage guide that can help me with this ?
Also i see that "fn":+ is added to the post aggregator is that expected ?
<img width="1426" alt="screen shot 2017-06-27 at 10 18 06 am" src="https://user-images.githubusercontent.com/26261686/27600835-0bb6f852-5b22-11e7-9ed7-57749603ca05.png">

**Comment by mailbaoer** [comment]
same too, with no data points! 😭

**Comment by abhisant** [comment]
This doesn't help you ?
http://druid.io/docs/latest/development/extensions-core/approximate-histograms.html

**Comment by nanittu** [comment]
@abhisant it appears that the plugin only supports quantiles on fields that have histogram sketches at ingestion time. I got it working only with those kind of fields. The expectation was it could work for both query time and ingest based
