### ISSUE TITLE
Issue with group by query type

### ISSUE THREAD

**Issue by sundaramprasad** [grafana-druid-plugin/druidplugin#22]
Hello,
I am trying to run a group-by query in Grafana. I used a pie chart to display data and granularity of 15 minutes. Ideally it should create a pie chart of the given group-by column with distinct elements in it and it should get updated every 5 second (refresh interval is 5 secs) for every 15 minutes interval like what happens in time series query with 15 mins granularity. 
But the data is not getting updated somehow. Can you help me to identify what the problem is?
Sundaram

**Comment by abhisant** [comment]
@sundaramprasad : I tried it, it's getting updated. 
Are you observing the query being fired . every 5 second in the network tab of your browser. Is the data changing by a noticeable amount ?

**Comment by sundaramprasad** [comment]
@abhisant : yes i observed and query is being fired every 5 seconds. And data is also changing by noticeable amount as it is clearly visible in timeseries query. Basically I have created a graph to see the realtime count of each values in a dimension. the dimension has only two possible values (yes and no). So i want to see the count of yes and no with incoming logs. But it's not getting plotted on timeseries graph properly. it's not updated with time. even when count is continuously increasing, its not increasing on the graph with time.

**Comment by sundaramprasad** [comment]
@abhisant : okay i got the problem. I was limiting the no of results to 2, but limiting it to 2 doesn't fetches more than 2 results. I misunderstood limit as limit for the number of distinct values in the given column. Now it's working as expected. Thanks!
