### ISSUE TITLE
Cardinality aggregator with grafana pluging

### ISSUE THREAD

**Issue by amoussoubaruch** [grafana-druid-plugin/druidplugin#24]
Hi,
For aggregation, can i use Cardinality aggregator with this pluging?

**Comment by nikhil2406** [comment]
@amoussoubaruch all existing aggregators works only with metric values as of now. I dont see cardinality aggregation option implemented currently.
was checking [druid documentation](http://druid.io/docs/latest/querying/aggregations.html) for cardinality aggregator which says "_Please note that this aggregator will be much slower than indexing a column with the hyperUnique aggregator_"
Not sure if it was deliberately not implemented in plugin.
Can you provide more information about your use-case? May be others also would be able to provide alternatives or else +1 your request.

thanks,
nikhil.

**Comment by amoussoubaruch** [comment]
@nikhil2406  Thanks for your answer! 

In my dataset i have only one metric value. I have many dimension columns. i want to do real time monitoring with IOT data that i take from kafka. One field is hostname. Data are provided by more country. 
My first goal is count how many distinct hostname for each country i have? 
Can you thinks that is it possible? 

Thanks,
ADB

**Comment by Gauravshah** [comment]
would hyperUnique not solve your problem ? It would be approximate though.
