### ISSUE TITLE
Question - Does this support logical filters?

### ISSUE THREAD

**Issue by kvsurii** [grafana-druid-plugin/druidplugin#27]
Thanks for creating this plugin! I have a question regarding filters. 
From what I see, we can "add tag" to add extra filters. Does this refer to an "and" type between each filter? Is there any way we can specify other logical filters like "OR" or "NOT".

**Comment by abhisant** [comment]
OR can be done by using "Add Query", the plugin will plot multiple lines on the same graph panel and NOT can be done using negation.

**Comment by Gauravshah** [comment]
@kvsurii if you want to plot it on the same line you can use regex filter with multiple values that would be close to single file OR. Multi field OR would be complicated on UI

**Comment by kvsurii** [comment]
Thanks  for the replies!
