### ISSUE TITLE
Grafana 4.0 support

### ISSUE THREAD

**Issue by hexchain** [grafana-druid-plugin/druidplugin#3]
First, thank you for the amazing plugin!

Right now this plugin does not seem to support Grafana 4.0. It gaves me the following JS error when trying to add a query:

```
TypeError: _.pluck is not a function
    at getMetricNames (http://xxx/public/plugins/abhisant-druid-datasource/datasource.js?bust=1482719877684:316:24)
    at DruidDatasource._doQuery (http://xxx/public/plugins/abhisant-druid-datasource/datasource.js?bust=1482719877684:120:25)
    at eval (http://xxx/public/plugins/abhisant-druid-datasource/datasource.js?bust=1482719877684:105:27)
    at Array.map (native)
    at DruidDatasource.query (http://xxx/public/plugins/abhisant-druid-datasource/datasource.js?bust=1482719877684:91:38)
    at eval (http://xxx/public/app/plugins/datasource/mixed/datasource.js?bust=1482719877684:4:494)
    at g (http://xxx/public/app/boot.fdf40765.js:38:29381)
    at http://xxx/public/app/boot.fdf40765.js:38:29553
    at o.$eval (http://xxx/public/app/boot.fdf40765.js:39:5194)
    at o.$digest (http://xxx/public/app/boot.fdf40765.js:39:3680)
```

**Comment by abhisant** [comment]
Thank you for reporting the bug. I will surely have a look into it and let
you know.

**Comment by hexchain** [comment]
I've tried replacing `_.pluck(array, field)` with `array.map(i => i[field])` which works great so far, except in a few places the `array` can be undefined.

Also, could you please add proper build scripts (like in http://grafana.org/blog/2016/04/08/timing-is-everything.-writing-the-clock-panel-plugin-for-grafana-3.0/) to this repo? Should be easier to contribute then.

Thanks!

**Comment by abhisant** [comment]
Sure, thanks. 
@hexchain , I will be traveling out of the country for a month and will be back on Feb 06. I am trying to windup my stuff before I leave. Will try my best to address your issue. Else, will work remotely and get back to you as soon as I can.

**Comment by abhisant** [comment]
Looks like this got introduced when the Grafana team added the following change:
upraded lodash to 4.15.0, closes #6021
Saw this in one of the datasource plugins: 
https://github.com/grafana/grafana/commit/649d9f91772c96d144ce770dce9d6b2a754ce227

**Comment by yacir** [comment]
@abhisant any news?

**Comment by knoguchi** [comment]
I suggest `_.map(objects, field)` or `_.map(objects, (e) => {....return ...})`syntax.  This way it wouldn't fail.

**Comment by abhisant** [comment]
Just updated the datasource.js and replaced pluck with map. 
"TypeError: _.pluck is not a function" -> This looks to be resolved. Yet to test remaining scenarios. 

Please copy the files from dist folder and replace it with the files in the folder:
grafana-<4.x.x>/data/plugins/abhisant-druid-datasource/.

**Comment by yacir** [comment]
Thanks @abhisant ! 

Might it be possible to release a new version (0.2.1) on [grafana plugins](https://grafana.net/plugins) ?

Thanks you in advance !

**Comment by abhisant** [comment]
@yacir : I am working on adding build scripts so that folks can contribute to the project. I was thinking on waiting for couple of more commits before releasing a new version. 
Will it be possible for you to copy the dist files in the datasource till then ? If not I can work with the Grafana team to have it released.

**Comment by abhisant** [comment]
Closing: TypeError: _.pluck is not a function -> The error no more exists. In case of any Grafana 4.0 support/issues, please open a new issue. I will release a new version soon. Will wait for next 1 week if there are any new commits / pulls to be included in the new version.
