### ISSUE TITLE
Support for latest version of lodash

### ISSUE THREAD

**Issue by pparkar** [grafana-druid-plugin/druidplugin#31]
Can you please update the script to support latest version of lodash
https://github.com/grafana-druid-plugin/druidplugin/blob/master/dist/query_ctrl.js#L285

Also any such occurrence elsewhere to use 'includes' over 'contains'. The above fix will allow the post-aggregator to be functional in grafana.

**Comment by pkarmaka** [comment]
@pparkar Are you facing any issue with the post agg feature?

**Comment by pparkar** [comment]
I am not able to add/invoke the post aggregator with the latest lodash version. 
https://lodash.com/docs/4.17.4#includes

Replacing 'contains' with 'includes' fixes the issue.
<img width="1433" alt="lodash-druid-grafana-error" src="https://user-images.githubusercontent.com/4753866/30246493-7504bcea-95b0-11e7-9575-e5ab285e616b.png">

**Comment by abhisant** [comment]
@pparkar , thanks for reporting it. You are welcome to send a pull, else I will get this done soon.
