### ISSUE TITLE
The 'null' value can't be filter

### ISSUE THREAD

**Issue by andresgomezfrr** [grafana-druid-plugin/druidplugin#32]
When you have a dimension without value it is `null`, but if you try to filter it using the UI it try to filter to the STRING "null" instead of `null` value.

**Comment by mhshimul** [comment]
You can use regex filter with value .+ or .*

**Comment by andresgomezfrr** [comment]
ok, this workaround works fine! Thanks :)

Could be interesting do some development to do it on selector filter??
