### ISSUE TITLE
Autofill is throwing errors

### ISSUE THREAD

**Issue by kvsurii** [grafana-druid-plugin/druidplugin#34]
When I try and autofill, I get this error. 

<img width="1427" alt="screen shot 2017-09-18 at 10 30 54 pm" src="https://user-images.githubusercontent.com/7862287/30577148-2f01e11a-9cc1-11e7-9abc-83e347a26f59.png">
To fix this, you will need to replace "target.datasource" to "target.druidDS" in https://github.com/grafana-druid-plugin/druidplugin/blob/master/src/datasource.js#L78

**Comment by Gauravshah** [comment]
Can you also send your grafana version ? It works with grafana 4.4.1. Been using on production

**Comment by kvsurii** [comment]
Grafana version - 4.5.1

**Comment by Gauravshah** [comment]
Out on a vacation as of now. Will look into it after 2 weeks.

**Comment by pkarmaka** [comment]
For me, I checked with v3.1.1

**Comment by Gauravshah** [comment]
@kvsurii can we do a screen share ? skype : "gauravmshah"
I am unable to see this on my production:
<img width="1404" alt="screen shot 2017-10-05 at 12 53 12 am" src="https://user-images.githubusercontent.com/620559/31216198-9fb2ede8-a967-11e7-9d09-512a525b6610.png">
using grafana 4.4.1
