### ISSUE TITLE
Druid plugin doesn't work on latest Grafana master

### ISSUE THREAD

**Issue by chinseone** [grafana-druid-plugin/druidplugin#37]
I built Grafana from master(0c31c7b10619088784bd28b31a4948e43d05d2bf) and installed Druid plugin as usual(putting it under /data/plugins folder), however when I tried to save Druid setting, following error occurred:
![error](https://user-images.githubusercontent.com/3478165/31256932-4df002d8-a9ea-11e7-820b-baf9b76d5144.jpg)
I checked Grafana code which says 

> // plugin module needs to export a constructor function named Datasource

But in [module.d.ts](https://github.com/grafana-druid-plugin/druidplugin/blob/master/dist/module.d.ts), DruidDatasource  is explicitly exported as Datasource, so not sure what happened... please help!

**Comment by abhisant** [comment]
Hi Cheng,

Could you please try cloning the latest changes. There are few fixes that went today morning.

Thank you,
Abhishek Sant

**Comment by chinseone** [comment]
Hi Abhishek,

Thanks for your quick reply. I tried latest code, but the error still happened.

Regards,

Li

**Comment by abhisant** [comment]
@Gauravshah : Is this because of any of your changes. Could you please help @chinseone . Else I can jump in if it's not related to your changes.

**Comment by Gauravshah** [comment]
@abhisant can you please take a look into it ? stuck for next couple of days

**Comment by chinseone** [comment]
Hi @abhisant ,

Are you able to reproduce this issue? My environment is:

node 6.9.0/8.6.0, both has same error
npm 3.10.8
Go 1.9

Thanks,

Li

**Comment by abhisant** [comment]
I will get back to you on this.

**Comment by pkarmaka** [comment]
I am on vacation currently, will be back in 3days. I can also have a look then. Thanks @abhisant for checking this.

**Comment by chinseone** [comment]
Hi @abhisant , just wanted to follow up on this issue. Any updates?

**Comment by abhisant** [comment]
@pkarmaka could you please look into it

**Comment by pkarmaka** [comment]
@chinseone which grafana version are you using

**Comment by chinseone** [comment]
@pkarmaka I build from master commit(0c31c7b), which is "4.6.0-pre1"

**Comment by pkarmaka** [comment]
Not sure exactly what but something may have changed in the Grafana master code. If you try 4.5.2, that's working.

**Comment by chinseone** [comment]
Do you think it's a plugin issue or Grafana's problem? If the later is the case, their next release will break stuff :(

**Comment by abhisant** [comment]
@pkarmaka : Can you check with the Grafana team? May be raise an issue or a query.

**Comment by nikhil2406** [comment]
@pkarmaka you are right. I checked grafana commit history, there seems to be some changes pushed related to systemjs and webpack module loading. I got same error in grafana tag 'latest' and '4.6.0-beta1'
Druid plugin is working fine with grafana 4.5.2.

![screen shot 2017-10-16 at 3 17 29 pm](https://user-images.githubusercontent.com/2122777/31637774-2b3a3396-b285-11e7-8515-dc4d7c69a0e7.png)

**Comment by daniellee** [comment]
This should be fixed in the latest Grafana master. We upgraded SystemJS which broke the import syntax for some plugins. We changed the SystemJS configuration and the Druid data source should work now.

**Comment by chinseone** [comment]
Thanks @daniellee and everyone for fixing this!

**Comment by kvsurii** [comment]
Thanks guys!
