### ISSUE TITLE
Post Aggregations Queries have disappeared.

### ISSUE THREAD

**Issue by clarkent86** [grafana-druid-plugin/druidplugin#39]
In at least Grafana version 4.4.2+ (tested on 4.6.0 as well) the following issue seems to have resurfaced: https://github.com/grafana-druid-plugin/druidplugin/issues/1

I am running the Druid plugin version 0.0.4

This issue is not present in Grafana version 4.2.0

Am I possibly missing a toggle to enable this feature?

**Comment by pkarmaka** [comment]
@clarkent86 Is the post agg row not present or the queries not firing?

**Comment by tollmanz** [comment]
I'm experiencing the same problem with Grafana 4.6.1 and Druid Plugin 0.0.4. I do not see the post aggregation rows in the UI.

**Comment by tollmanz** [comment]
As an update, I do now see post aggregations; however, the published version hosted by Grafana (https://grafana.com/api/plugins/abhisant-druid-datasource), was last updated in February, which does not include the fixed discussed in #1 and merged with f6ad92c855f34dd6a8c151adcdb654d5259a2f0e.

Can the plugin authors push an update to Grafana's plugin hosting? I think this will help clear up confusion.

**Comment by clarkent86** [comment]
As @tollmanz said, I do not see the row at all for post aggregations @pkarmaka.

**Comment by tollmanz** [comment]
@clarkent86 If you manually install the plugin from master, do you see the row again?

**Comment by clarkent86** [comment]
@tollmanz I just took you at your word, I assume it would! If I get some time today I will confirm & report back. The issue with this is we are only sourcing Grafana hosted plugins so I would be interested in seeing the official version here getting hosted by Grafana.

**Comment by pkarmaka** [comment]
Thanks for the update @tollmanz. I'll update the version hosted by Grafana.

**Comment by pkarmaka** [comment]
https://github.com/grafana-druid-plugin/druidplugin/issues/44
