### ISSUE TITLE
Could you please do a new release for a stable version

### ISSUE THREAD

**Issue by gavinmcnair** [grafana-druid-plugin/druidplugin#44]
The last stable version was in February.

**Comment by pkarmaka** [comment]
This will be taken care of

**Comment by dene14** [comment]
@pkarmaka how do you know? :)

Guys, seriously, can you please bump the version? Really suffering here.

**Comment by pkarmaka** [comment]
Sorry for the delay. Will do it today. You can get the code from here as well. The dist is checked in.

**Comment by dene14** [comment]
Right, but when you use official grafana docker images there is the only one sane approach to install plugins - from grafana's repository.

That's why it hurts some people.

**Comment by pkarmaka** [comment]
https://github.com/grafana/grafana-plugin-repository/pull/221

**Comment by dene14** [comment]
Much appreciated!
