### ISSUE TITLE
Trying to add cardinality support

### ISSUE THREAD

**Issue by gavinmcnair** [grafana-druid-plugin/druidplugin#46]
Cardinality is supported in Druid but doesn't appear to be part of the plugin.

While its appreciated that hyperlogs are needed in most use cases sometimes cardinality is useful.

The ongoing effort is at

https://github.com/gavinmcnair/druidplugin

Please feel free to tell me anything im doing wrong since i am no JS expert.

**Comment by gavinmcnair** [comment]
A further update has been made to this so that it doesn't error. If there is an angular expert who knows how this can be neatly refactored please speak up :)

**Comment by kvsurii** [comment]
you can send out a PR when done :) we can review it

**Comment by gavinmcnair** [comment]
I have created a PR https://github.com/grafana-druid-plugin/druidplugin/pull/48 please do review.

**Comment by gavinmcnair** [comment]
@kvsurii can someone please do a review?

**Comment by gavinmcnair** [comment]
@pkarmaka can we please get an update on this. This project has a lot of potential but is getting a serious lack of attention at the moment.
