### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by gavinmcnair** [grafana-druid-plugin/druidplugin#51]
I was wondering if this project is being actively maintained.

I see the occasional direct commit to master (which look like they are fixing the issues of an individual user who has commit access).

I would like to see a more active community around this very useful plugin. There is still a lot of untapped potential.

**Comment by pkarmaka** [comment]
Thanks for the feedback. There has been some reduction in the number of people maintaining this. We'll try to make it better. It's an open community.. everyone is welcome to make contributions to keep this running.

**Comment by gavinmcnair** [comment]
I know this issue is closed but people are contributing. There are 4 pull requests at the moment. We should be trying to get a merge in every few weeks.
