### ISSUE TITLE
support for granularity : week, month, quarter , year

### ISSUE THREAD

**Issue by robbig2871** [grafana-druid-plugin/druidplugin#54]
Regarding druid documentation http://druid.io/docs/latest/querying/granularities.html supported granularity strings are: all, none, second, minute, fifteen_minute, thirty_minute, hour, day, week, month, quarter and year.

driudplugin limitation: customGranularities = ['minute', 'fifteen_minute', 'thirty_minute', 'hour', 'day', 'all'];

Please add support for all supported granularity.

**Comment by pkarmaka** [comment]
https://github.com/grafana-druid-plugin/druidplugin/pull/45
Expecting more changes here.
