### ISSUE TITLE
Plugin doesn't send any requests to druid

### ISSUE THREAD

**Issue by PetarLotrean** [grafana-druid-plugin/druidplugin#60]
I tried installing the plugin on grafana 5.x and grafana 4.x, same results. 

Issue:
When creating a simple query on a simple dataset, e.g. timeseries with hourly aggregate which is a sum of one dimension which is just a count, there are no requests made to the druid server.
When inspecting what happens in the code, it seems that in most of the input combinations (query types, filters, aggregations) [this](https://github.com/grafana-druid-plugin/druidplugin/blob/1abc4831c4add929084055dddf2eae7db33dce05/dist/datasource.js#L123) if function doesn't pass because target.aggregators isn't defined at the point of execution.

I tried sending requests manually (not through grafana) and druid sends normal responses.

The only query that triggers a request to druid is the select query. All others trigger weird query requests.

This is one that doesn't trigger a request at all (notice the circle thingy in query inspector):
![image](https://user-images.githubusercontent.com/3826981/40725409-a70af000-6423-11e8-8b22-1e7633da2bb0.png)

And here's one that triggers a "TopN" query type request when I selected timeseries query with a filter and count aggregator:
![image](https://user-images.githubusercontent.com/3826981/40725552-02c6d918-6424-11e8-9f7a-113e49d3f334.png)

**Comment by irltankman** [comment]
+1, We are trying to use druid plugin v0.0.5 with Grafana v5.1.3 and we are not getting any responses to a TopN query 
![grafana-druid](https://user-images.githubusercontent.com/28203109/43152975-efdc2e74-8f67-11e8-956c-8c7906d70004.png)

**Comment by PetarLotrean** [comment]
We figured it out accidentally, click on the small add tag button at the end of aggregations line, it is then that the aggregations are considered...

**Comment by RestfulBlue** [comment]
lmao xD

**Comment by irltankman** [comment]
I want to hug you :)

**Comment by PetarLotrean** [comment]
You don't want to know how many engineer-hours were spent trying to figure this out :D

**Comment by irltankman** [comment]
Thankfully i only had to spend about 5 mins and you helped me :)

**Comment by knoguchi** [comment]
"Add tag" came from bad copy and paste.   It really should be "Add agg"
