### ISSUE TITLE
error on Timeseries with Grafana 4.1.2

### ISSUE THREAD

**Issue by tutunci** [grafana-druid-plugin/druidplugin#8]
Hi,
I've update Grafana from 3 to 4.1.2 .
After that, I've had issues that I've seen was fixed recently.
My charts also uses Timeseries and here I've the error described below.

Error title:
Cannot read property 'toString' of undefined

Error description:
`TypeError: Cannot read property 'toString' of undefined
    at a.isMsResolutionNeeded (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:21:3590)
    at new a (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:21:934)
    at a.timeSeriesHandler (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:18:29092)
    at http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:18:28273
    at Array.map (native)
    at a.getSeriesList (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:18:28246)
    at b.onDataReceived (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:19:3247)
    at f.emit (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:52:2928)
    at a.emit (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:52:5256)
    at b.handleQueryResult (http://10.20.50.249:3000/public/app/boot.6d63bd8b.js:46:4942)`

**Comment by abhisant** [comment]
Let me have a look into it.

**Comment by evgmitskevich** [comment]
I have the same issue. Looks like only topN charts are affected.

**Comment by abhisant** [comment]
I am working out with Grafana team to understand what exactly changed. According to them there is no breaking change in the plugin except the Lodash version upgrade. They have asked for further details, please follow the link below.

https://github.com/grafana/grafana/issues/7581

**Comment by knoguchi** [comment]
It works fine for me.  I'm using the HEAD of Grafana v4.1.x branch, compiled from source, and the HEAD of master branch of the druidplugin compiled from source (Thanks for the build script!).

**Comment by abhisant** [comment]
@knoguchi : It's surprising because even I am seeing the issues in topN and groupBy.

**Comment by abhisant** [comment]
git diff dist has lots of differences - Yes, I have just checked in build related files..

**Comment by knoguchi** [comment]
Created PR #9 to fix the topN.  I noticed my compilation had a problem that I reported earlier.

**Comment by abhisant** [comment]
@knoguchi : Thank you for all the pull's and identifying the issue. Instead of a branch I was thinking to put a git tag, because anyways when I release the grafana version, they take the commitId and all commits before the particular commitId are taken into the consideration. Please let me know if you are ok with creating a tag instead of branch.

**Comment by knoguchi** [comment]
tag is fine.

**Comment by abhisant** [comment]
Issued a pull request to the Grafana team to release 0.0.3 and 0.0.4. (Release notes at: https://github.com/grafana/grafana-plugin-repository/pull/99)

The fix is available in the dist folder. Till the version is released the dist files can be copied to fix the issues.

**Comment by tutunci** [comment]
Thanks!
I've manually updated the plugin and now it's working fine.

Thanks a lot!
M.

**Comment by abhisant** [comment]
https://grafana.net/plugins/abhisant-druid-datasource?version=0.0.4
