### ISSUE TITLE
Project status ? looking for new maintainers ?

### ISSUE THREAD

**Issue by jbguerraz** [grafana-druid-plugin/druidplugin#91]
Hello,

Despite Superset is there, we tend to believe Grafana is a better fit for system-wide dashboarding needs.
This plugin then looks required, OTOH, we can see there are issues and merge requests awaiting and not much traction.
Did you stopped using Druid ? or stopped using Grafana ? Is there a good reason about it we should know ? :)
Otherwhise, are you open to give maintainership to anyone else so issues and pull requests could be processed ?
Thank you for your efforts :)

cc @abhisant @Gauravshah @pranit22

**Comment by Gauravshah** [comment]
we started using our forked version https://github.com/GoshPosh/druidplugin

**Comment by abhisant** [comment]
Hi Gaurav, 

Would you like to maintain ? 

Thank you,
Abhishek Sant

**Comment by Gauravshah** [comment]
thanks I will have to check with the team here and check if they have bandwidth to take it.
but I am curios did you guys move our of druid to something else ?

**Comment by jbguerraz** [comment]
Happy to get such quick feedback :)

@abhisant may I ask why you don't care much by now about this plugin ? this is very interesting to me :)
@Gauravshah if we validate our intention to use Druid, Superset and Grafana all togethers, then we'll be happy helping maintaining it !

**Comment by abhisant** [comment]
Hi, 

I have actually moved out of the Infrastructure team and now I am not getting lot of bandwidth to followup on this. I can still continue to maintain it.

Thank you,
Abhishek Sant

**Comment by jbguerraz** [comment]
@abhisant it's awesome you can still maintain it! the infrastructure team is still using it ? just not contributing back ? or still using old grafana ?
@Gauravshah do you think you guys can join @abhisant, helping maintaining it ?
We're new to it, but we (the Skilld small devops team) will be happy to join maintainers and help processing the issue queue, reviewing the pull requests (despite our skills on this plugin are near zero for now: the best is enemy of the good ;)) and surely participate on work to get it running with Grafana 6 ( #92 )

**Comment by Gauravshah** [comment]
@jbguerraz we should be able contribute on new features & reviewing PRs. There are few additional features on Poshmark repo, will try to see if we can re-open PRs

**Comment by iamshreeram** [comment]
@Gauravshah, Do you still plan to maintain this repo at poshmark? Does this plugin still support the latest grafana 6.x.x?

**Comment by iamshreeram** [comment]
@Gauravshah, Do you have any plans to maintain this repo at poshmark? Does this plugin support the latest grafana 6.x.x?

**Comment by mickymiek** [comment]
@iamshreeram we're using it with the latest grafana and it works well.

**Comment by iamshreeram** [comment]
@mickymiek , 
Project description is mis-leading. It says "This repository contains the druid plugin for Grafana 3.0". 

Is there any docs available for this plugin to plot time series from druid?

**Comment by iamshreeram** [comment]
@mickymiek , Project description is mis-leading. It says "This repository contains the druid plugin for Grafana 3.0".
Is there any docs available for this plugin to plot time series from druid? Can some one help me with #94

**Comment by Gauravshah** [comment]
@iamshreeram it does work well with 6.2, we are using it on production. Have not tried 6.3 ( but should work theoretically)
we do have a fork at Poshmark that has additional features. if @abhisant has time I can open PRs back to this repo

**Comment by jbguerraz** [comment]
@abhisant could add @Gauravshah and @mickymiek (and or me, we're in same team) as maintainers maybe ? so we can revive this repo :)

**Comment by jbguerraz** [comment]
@abhisant @pranit22 maybe one of you could add some maintainers here ? like @Gauravshah  and @mickymiek  and myself ?

**Comment by Gauravshah** [comment]
@abhisant we should look at taking help from @jbguerraz & @mickymiek  ?

**Comment by abhisant** [comment]
Sure. I will add @jbguerraz <https://github.com/jbguerraz>, @mickymiek <https://github.com/mickymiek> and @Gauravshah <https://github.com/Gauravshah> as collaborators. Thank you so much guys for help.

**Comment by abhisant** [comment]
@Gauravshah - Bad news. 
"grafanadruidplugin@gmail.com" - Was an email id I created to maintain this repo. I had given write permissions to my personal account "abhisant" and one of the collaborators "pranit22". 

Looks like google deleted this account - grafanadruidplugin@gmail.com for no reason :( 
Whenever I try logging in, it says google account not found. Looks like it's deleted for ever. 

I can't add any new collaborators. But I can surely merge PR's. Let me know which PR's do you want me to merge. Or you guys can create one PR which would revive this repo and I can merge it.

**Comment by Gauravshah** [comment]
thanks @abhisant 
lets try opening a github support case I am sure they would be able to help.

There will be a lot of PRs I am thinking. collaboration would help in terms of review as well

**Comment by abhisant** [comment]
Sure.

**Comment by abhisant** [comment]
Added you guys as collaborators :). Thank you for your extended help guys.

**Comment by mickymiek** [comment]
Thanks a lot @abhisant

**Comment by jbguerraz** [comment]
Thank you! let's get started :)

**Comment by jbguerraz** [comment]
@Gauravshah ok for you as well ? let's close it ?
